const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: "120",
      band: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High Queality product",
    },
    {
      _id: "2",
      name: "Adidas Slim Shirts",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: "140",
      band: "Adidas",
      rating: 5,
      numReviews: 8,
      description: "High Queality product",
    },
    {
      _id: "3",
      name: "Karate Slim Shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: "220",
      band: "Karate",
      rating: 4.0,
      numReviews: 12,
      description: "High Queality product",
    },
    {
      _id: "4",
      name: "Vans Slim Pants",
      category: "Pants",
      image: "/images/p4.jpg",
      price: "250",
      band: "Vans",
      rating: 4.5,
      numReviews: 9,
      description: "High Queality product",
    },
    {
      _id: "5",
      name: "Converse Slim Pants",
      category: "Pants",
      image: "/images/p5.jpg",
      price: "150",
      band: "Converse",
      rating: 3.5,
      numReviews: 15,
      description: "High Queality product",
    },
    {
      _id: "6",
      name: "Cheroke Slim Pants",
      category: "Pants",
      image: "/images/p6.jpg",
      price: "100",
      band: "Cheroke",
      rating: 4.0,
      numReviews: 8,
      description: "High Queality product",
    },
  ],
};
export default data;
